[project]
name = "active-learning-flywheel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "fastai>=2.7.18",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]
