name: docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-deps ".[docs]"
                  pip install jupyter nbconvert ipykernel
            
            - name: Generate docs
              run: |
                  cp README.md docs/index.md
                  jupyter nbconvert nbs/imagenette/quickstart.ipynb --to markdown --output-dir docs/
                  sed -i 's/\x1b\[[0-9;]*m//g' docs/quickstart.md

            - name: Deploy
              run: mkdocs gh-deploy --force
